---
UP:
  drop_table:
    - countries
DOWN:
  create_table:
    countries:
      country_name:
        type: string
        null: false
        default:
        length: 255
      country_slug:
        type: string
        null: false
        default:
        length: 255
