---
DOWN: 
  drop_table: 
    - acos
UP: 
  create_table: 
    acos: 
      parent_id: 
        type: integer
        null: true
        default: 
        length: 11
      model:
        type: string
        null: true
        default: ""
        length: 255
      foreign_key:
        type: integer
        null: true
        length: 11
      alias:
        type: string
        null: true
        length: 255
      lft:
        type: integer
        null: true
        length: 11
      rght:
        type: integer
        null: true
        length: 11